baseURL: https://ayedaemon.github.io/
languageCode: en-us
title: Connected
theme: "hugo-PaperMod"


# googleAnalytics: UA-123-45

paginate: 5
buildDrafts: false
buildFuture: false
enableGitInfo : true

minify:
  disableXML: true
  minifyOutput: true


params:
  env: production
  title: "Connected"
  description: "Ayedaemon's blog"
  keywords: [Blog, ayedaemon, PaperMod]
  author: ["ayedaemon"]
  DateFormat: "January 2, 2006"

  defaultTheme: dark # dark, light, auto
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  ShowFullTextinRSS: true


  # home-info mode
  homeInfoParams:
    Title: "Ayedaemon"
    Content: An Information Security Engineer from India who is interested in DevOps culture and Security that isn’t based on Excel.

  socialIcons:
    - name: linkedin
      url: "https://linkedin.com/in/ayedaemon"
    - name: mastodon
      url: "https://social.linux.pizza/@ayedaemon"
    - name: github
      url: "https://github.com/ayedaemon/"
    - name: email
      url: "mailto:ayedaemon@gmail.com"



  editPost:
    URL: "https://github.com/ayedaemon/ayedaemon.github.io/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: categories
      name: Archives
      url: /archives/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 30
    - identifier: series
      name: Series
      url: /series/
      weight: 40
    # - identifier: about
    #   name: About
    #   url: /about/
    #   weight: 30

pygmentsUseClasses: true
markup:
    # goldmark:
    #     renderer:
    #         unsafe: true
    highlight:
        anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: false
        # noClasses: false
        style: monokai


taxonomies:
    category: categories
    tag: tags
    series: series


outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary for searching
