baseURL: https://ayedaemon.github.io/
languageCode: en-us
title: "Connected"
theme: ["PaperMod"]


paginate: 5
buildDrafts: false
buildFuture: false
enableGitInfo : true

minify:
  disableXML: true
  minifyOutput: true

params:
  # home-info mode
  homeInfoParams:
    Title: "Ayedaemon"
    Content: "An Information Security Engineer from India who is interested in DevOps culture and Security that isn’t based on Excel."

  socialIcons:
    - name: Linkedin
      url: "https://linkedin.com/in/ayedaemon"
    - name: Mastodon
      url: "https://social.linux.pizza/@ayedaemon"
    - name: email
      url: "mailto:ayedaemon@gmail.com"


  env: "production"
  description: "Blogs where I try to connect technical dots"
  author: ["ayedaemon"]
  keywords: ["blog", "ayedaemon", "connect3d"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark

  hideSummary: false
  comments: false
  tocopen: false


  ShowWordCount: true
  ShowBreadCrumbs: false
  ShowPostNavLinks: false
  ShowReadingTime: true
  ShowShareButtons: false
  ShowCodeCopyButtons: true
  ShowFullTextinRSS: true
  ShowRssButtonInSectionTermList: true
  showtoc: true



  disableThemeToggle: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  disableAnchoredHeadings: false

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"] ##  can be less but not more than shown in list

  editPost:
    URL: "https://github.com/ayedaemon/ayedaemon.github.io/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link




menu:
  main:
    - identifier: categories
      name: Archives
      url: /archives/
      weight: 1
    - identifier: series
      name: Series
      url: /series/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 30
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 30


pygmentsUseClasses: true
markup:
  highlight:
    # noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: false
    style: monokai

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

taxonomies:
  tag: tags
  series: series